#!/usr/bin/env sh

# commit_msg_file=$1

# # Read the commit message from the file
# commit_msg=$(cat "$commit_msg_file")

# # Define the regex pattern for the commit message format
# commit_msg_pattern="^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+"

# # Check if the commit message matches the pattern
# if ! [[ $commit_msg =~ $commit_msg_pattern ]]; then
#     echo "Invalid commit message format. Please follow the convention: <type>(<scope>): <message>"
#     exit 1
# fi


# commitlint -E HUSKY_GIT_PARAMS
npx --no -- commitlint --edit $1